spring.application.name=documentos.api

spring.datasource.url=jdbc:postgresql://localhost:5432/docs_system_consult
spring.datasource.username=postgres
spring.datasource.password=03032011

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true