CREATE TABLE public.solicitacoes (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    aluno_id int4 NOT NULL,
    curso_id int4 NOT NULL,
    tipo_documento_id int4 NOT NULL,
    status_id int4 NOT NULL,
    data_solicitacao timestamptz NOT NULL,
    data_alteracao timestamptz NULL,
    prioridade varchar(20) NOT NULL,
    CONSTRAINT solicitacoes_pkey PRIMARY KEY (id)
);

ALTER TABLE public.solicitacoes ADD CONSTRAINT aluno_id FOREIGN KEY (aluno_id) REFERENCES public.alunos(id);
ALTER TABLE public.solicitacoes ADD CONSTRAINT curso_id FOREIGN KEY (curso_id) REFERENCES public.cursos(id);
ALTER TABLE public.solicitacoes ADD CONSTRAINT status_id FOREIGN KEY (status_id) REFERENCES public.status(id);
ALTER TABLE public.solicitacoes ADD CONSTRAINT tipo_documento_id FOREIGN KEY (tipo_documento_id) REFERENCES public.tipo_documentos(id);