CREATE TABLE public.historico (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    solicitacao_id int4 NOT NULL,
    status_anterior_id int4 NOT NULL,
    status_novo_id int4,
    responsavel varchar(100) NOT NULL,
    data_alteracao timestamptz NOT NULL,
    CONSTRAINT historico_pkey PRIMARY KEY (id)
);

ALTER TABLE public.historico ADD CONSTRAINT solicitacao_id FOREIGN KEY (solicitacao_id) REFERENCES public.solicitacoes(id);
ALTER TABLE public.historico ADD CONSTRAINT status_anterior_id FOREIGN KEY (status_anterior_id) REFERENCES public.status(id);
ALTER TABLE public.historico ADD CONSTRAINT status_novo_id FOREIGN KEY (status_novo_id) REFERENCES public.status(id);